    <!-- BEGIN: Content-->
    <div class="app-content content ">
        <div class="content-overlay"></div>
        <div class="header-navbar-shadow"></div>
        <div class="content-wrapper">
            <div class="content-header row">
                <div class="content-header-left col-md-9 col-12 mb-2">
                    <div class="row breadcrumbs-top">
                        <div class="col-12">
                            <h2 class="content-header-title float-left mb-0">
                                <b><?php foreach ($_SESSION['submenus'] as $menu) { ?>
                                        <?php if ($this->_controlador == $menu['v_link']) {
                                            echo $menu['v_descripcion'];
                                        } else {
                                            '';
                                        } ?>
                                    <?php } ?>
                                </b>
                            </h2>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <section class="col-lg-6">
                    <div class="card card-secondary">
                        <div class="card-header">
                            <h4 class="card-title text-white"><b>Filtro por fechas</b></h4>
                        </div>
                        <div class="card-body">
                            <br>
                            <div class="row">
                                <div class="form-group col-md-6">
                                    <label class="form-label font-weight-bolder">Fecha inicio:</label>
                                    <div class="input-group">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text"><i class="far fa-calendar-alt"></i></span>
                                        </div>
                                        <input type="text" id="finicio" tabindex="1" class="form-control flatpickr-basic" value="<?php echo date("Y-m-d") ?>" placeholder="YYYY-MM-DD" />
                                    </div>
                                </div>
                                <div class="form-group col-md-6">
                                    <label class="form-label font-weight-bolder">Fecha fin:</label>
                                    <div class="input-group">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text"><i class="far fa-calendar-alt"></i></span>
                                        </div>
                                        <input type="text" id="ffin" tabindex="2" class="form-control flatpickr-basic" value="<?php echo date("Y-m-d") ?>" placeholder="YYYY-MM-DD" />
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="form-group col-sm-6">
                                    <button id="btnfiltrofecha" tabindex="3" type="button" class="btn btn-success btn-block"><b>Filtrar fechas</b></button>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
                <section class="col-lg-6">
                    <div class="card card-secondary">
                        <div class="card-header">
                            <h4 class="card-title text-white"><b>Filtro personalizado</b></h4>
                        </div>
                        <div class="card-body">
                            <br>
                            <div class="row">
                                <div class="col-xs-12 col-sm-12 col-12">
                                    <button id="btnfiltro" type="button" class="btn btn-success btn-block font-weight-bolder" style="color: White;">
                                        <i class="fas fa-filter"></i><span>&nbsp;&nbsp;Aplicar filtro personalizado</span>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
                <section class="col-lg-12">
                    <div class="card col-12">
                        <div class="card-body">
                            <div class="row">

                                <div class="col-md-12 col-12">
                                    <table id="example1" class="table table-bordered">
                                        <thead class="thead-dark">
                                            <tr class="text-center">
                                                <th>#</th>
                                                <th>RUC</th>
                                                <th>Razon Social</th>
                                                <th>Fecha</th>
                                                <th>Código Producto</th>
                                                <th>Nombre Producto</th>
                                                <th>Documento Cliente</th>
                                                <th>Nombre Cliente</th>
                                                <th>Tipo Cliente</th>
                                                <th>Departamento</th>
                                                <th>Provincia</th>
                                                <th>Distrito</th>
                                                <th>Ventas</th>
                                                <th>kilos</th>
                                                <th>Cantidades</th>
                                            </tr>
                                        </thead>
                                        <tbody id="table">
                                        </tbody>
                                    </table>
                                </div>

                            </div>
                        </div>
                    </div>
                </section>
            </div>

        </div>
    </div>
    <!-- END: Content-->

    <!-- MODAL INSERTANDO -->
    <div class="modal fade" id="modal-filtro" data-backdrop="static" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title"><b>APLICAR FILTRO PARA REPORTE DE VENTAS...</b></h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">

                    <div class="row">
                        <div class="form-group col-md-6">
                            <label class="form-label font-weight-bolder">Fecha inicio:</label>
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="far fa-calendar-alt"></i></span>
                                </div>
                                <input type="text" id="fechainicio" tabindex="1" class="form-control flatpickr-basic" value="<?php echo date("Y-m-d") ?>" placeholder="YYYY-MM-DD" />
                            </div>
                        </div>
                        <div class="form-group col-md-6">
                            <label class="form-label font-weight-bolder">Fecha fin:</label>
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="far fa-calendar-alt"></i></span>
                                </div>
                                <input type="text" id="fechafin" tabindex="2" class="form-control flatpickr-basic" value="<?php echo date("Y-m-d") ?>" placeholder="YYYY-MM-DD" />
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="form-group col-sm-6">
                            <button id="btnfecha" tabindex="3" type="button" class="btn btn-success btn-block"><b>Cargar datos</b></button>
                        </div>
                    </div>

                    <div class="row">
                        <div class="form-group col-md-12">
                            <label class="form-label font-weight-bolder">Departamento:</label>
                            <select id="departamento" tabindex="4" class="select2 form-control departamento" multiple>
                            </select>
                        </div>
                    </div>

                    <div class="row">
                        <div class="form-group col-md-12">
                            <label class="form-label font-weight-bolder">Distrito:</label>
                            <select id="distrito" tabindex="5" class="select2 form-control distrito" multiple>
                            </select>
                        </div>
                    </div>

                    <div class="row">
                        <div class="form-group col-md-12">
                            <label class="form-label font-weight-bolder">Distribuidor:</label>
                            <select id="ruc" tabindex="6" class="select2 form-control distribuidor" multiple>
                            </select>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="row">
                            <div class="col-sm-6">
                                <button id="btnaceptar" tabindex="7" type="button" class="btn btn-success btn-block"><b>Filtrar</b></button>
                            </div>
                            <br>
                            <br>
                            <div class="col-sm-6">
                                <button id="btncancelar" tabindex="8" type="button" class="btn btn-danger btn-block"><b>Cancelar</b></button>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>