    <!-- BEGIN: Content-->
    <div class="app-content content ">
        <div class="content-overlay"></div>
        <div class="header-navbar-shadow"></div>
        <div class="content-wrapper">
            <div class="content-header row">
                <div class="content-header-left col-md-9 col-12 mb-2">
                    <div class="row breadcrumbs-top">
                        <div class="col-12">
                            <h2 class="content-header-title float-left mb-0">
                                <b><?php foreach ($_SESSION['submenus'] as $menu) { ?>
                                        <?php if ($this->_controlador == $menu['v_link']) {
                                            echo $menu['v_descripcion'];
                                        } else {
                                            '';
                                        } ?>
                                    <?php } ?>
                                </b>
                            </h2>
                        </div>
                    </div>
                </div>
            </div>



            <div class="row">
                <section class="col-lg-8">
                    <div class="card col-12">
                        <div class="card-body">
                            <div class="row">

                            <iframe title="BIVentas" width="1024" height="600" src="https://app.powerbi.com/view?r=eyJrIjoiYzg5ZDJjMjAtNzZmMi00MDlmLTg0NGQtZjNiYmIwZWVkZDAwIiwidCI6IjI1MTJiYzc2LTBiNDItNDUyMS05YTUwLWU3MmVhZTNkYjVjYSJ9" frameborder="0" allowFullScreen="true">
                            </iframe>

                                <!-- <div class="col-md-12 col-12">
                                    <table id="example1" class="table table-bordered">
                                        <thead class="thead-dark">
                                            <tr class="text-center">
                                                <th>#</th>
                                                <th>RUC</th>
                                                <th>Razon Social</th>
                                                <th>Fecha</th>
                                                <th>Código Producto</th>
                                                <th>Nombre Producto</th>
                                                <th>kilos</th>
                                                <th>Cantidades</th>
                                            </tr>
                                        </thead>
                                        <tbody id="table">
                                        </tbody>
                                    </table>
                                </div> -->

                            </div>
                        </div>
                    </div>
                </section>
            </div>

        </div>
    </div>
    <!-- END: Content-->