    <!-- BEGIN: Content-->
    <div class="app-content content ">
        <div class="content-overlay"></div>
        <div class="header-navbar-shadow"></div>
        <div class="content-wrapper">
            <div class="content-header row">
                <div class="content-header-left col-md-9 col-12 mb-2">
                    <div class="row breadcrumbs-top">
                        <div class="col-12">
                            <h2 class="content-header-title float-left mb-0">
                                <b><?php foreach ($_SESSION['menus'] as $menu) { ?>
                                        <?php if ($this->_controlador == $menu['v_link']) {
                                            echo $menu['v_descripcion'];
                                        } else {
                                            '';
                                        } ?>
                                    <?php } ?>
                                </b>
                            </h2>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <section class="col-lg-6">
                    <div class="card card-secondary">
                        <div class="card-header">
                            <h4 class="card-title text-white"><b>Cargar archivo (*.xls,*.xlsx)</b></h4>
                        </div>
                        <div class="card-body">
                            <br>
                            <div class="row">
                                <div class="form-group col-md-12">
                                    <div class="input-group">
                                        <label class="form-label font-weight-bolder">Seleccionar archivo:</label>
                                        <div class="input-group">
                                            <input id="documento" name="documento" type="file">
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-xs-12 col-sm-12 col-12">
                                    <button id="btnsubir" type="button" class="btn btn-success btn-block font-weight-bolder" style="color: White;">
                                        <i class="fa-solid fa-upload fa-beat"></i>
                                        <span>&nbsp;&nbsp;Subir archivo</span>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
                <section class="col-lg-6">
                    <div class="card card-secondary">
                        <div class="card-header">
                            <h4 class="card-title text-white"><b>Formato archivo inventario</b></h4>
                        </div>
                        <div class="card-body">
                            <br>
                            <div class="row">
                                <div class="col-sm-12">
                                    <form action="<?php echo BASE_URL ?>subirstock/descargar_formato" method="post">
                                        <button id="btnformato" type="submit" class="btn btn-success btn-block font-weight-bolder" style="color: White;">
                                            <i class="fa-solid fa-file-excel fa-beat"></i>
                                            <span>&nbsp;&nbsp;Formato Stock en Excel (*.xls)</span>
                                        </button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
                <section class="col-lg-12">
                    <div class="card col-12">
                        <div class="card-body">
                            <div class="row">

                                <div class="col-md-12 col-12">
                                    <table id="example1" class="table table-bordered">
                                        <thead class="thead-dark">
                                            <tr class="text-center">
                                                <th># Id</th>
                                                <th>RUC</th>
                                                <th>Razon Social</th>
                                                <th>Archivo</th>
                                                <th>Fecha</th>
                                                <th># Registros</th>
                                                <th>Usuario</th>
                                                <th># Archivo</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <?php if (isset($this->stockruc)) { ?>
                                                <?php foreach ($this->stockruc as $tr) { ?>
                                                    <tr>
                                                        <td class="text-center"><?php echo $tr['i_id'] ?></td>
                                                        <td class="text-left"><?php echo $tr['v_ruc'] ?></td>
                                                        <td class="text-left"><?php echo $tr['v_razon'] ?></td>
                                                        <td class="text-left"><?php echo $tr['v_archivo'] ?></td>
                                                        <td class="text-center"><?php echo $tr['v_fecha'] ?></td>
                                                        <td class="text-center"><?php echo $tr['v_registros'] ?></td>
                                                        <td class="text-left"><?php echo $tr['v_nombres'] ?></td>
                                                        <td class='text-center'>
                                                            <a href='<?php echo BASE_URL ?>subirstock/descargar_archivo/&archivo=<?php echo $tr['v_archivo'] ?>&ruc=<?php echo $tr['v_ruc'] ?>' class='btn btn-warning btn-sm text-black' target="_blank">
                                                                <i class="fa-solid fa-download"></i><b>&nbsp;&nbsp;*.xlsx</b>
                                                            </a>
                                                        </td>
                                                    </tr>
                                                <?php } ?>
                                            <?php } ?>
                                        </tbody>
                                    </table>
                                </div>

                            </div>
                        </div>
                    </div>
                </section>
            </div>

        </div>
    </div>
    <!-- END: Content-->

    <!-- MODAL INSERTANDO -->
    <div class="modal fade" id="modal-insert" data-backdrop="static" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">CARGANDO DATOS...</h5>
                    <!-- <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button> -->
                </div>
                <div class="modal-body">
                    <p>
                        Se estan cargando los datos, favor de no cerrar la ventana
                    </p>
                    <p>
                        Tiempo transcurrido: <b id="number"></b> segundos
                    </p>
                </div>
            </div>
        </div>
    </div>