    <!-- BEGIN: Content-->
    <div class="app-content content ">
        <div class="content-overlay"></div>
        <div class="header-navbar-shadow"></div>
        <div class="content-wrapper">
            <div class="content-header row">
                <div class="content-header-left col-md-9 col-12 mb-2">
                    <div class="row breadcrumbs-top">
                        <div class="col-12">
                            <h2 class="content-header-title float-left mb-0">
                                <b><?php foreach ($_SESSION['menus'] as $menu) { ?>
                                        <?php if ($this->_controlador == $menu['v_link']) {
                                            echo $menu['v_descripcion'];
                                        } else {
                                            '';
                                        } ?>
                                    <?php } ?>
                                </b>
                            </h2>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <section class="col-lg-12">
                    <div class="card card-secondary">
                        <div class="card-header">
                            <h4 class="card-title text-white"><b>Filtro por fechas</b></h4>
                        </div>
                        <div class="card-body">
                            <br>
                            <div class="row">
                                <div class="form-group col-md-4">
                                    <label class="form-label font-weight-bolder">Distribuidor:</label>
                                    <select id="ruc" tabindex="1" class="select2 form-control distribuidor">
                                        <option value="00000000000" selected disabled>-- SELECCIONE --</option>
                                        <?php echo $this->filasdis ?>
                                    </select>
                                    <div id="msj-ruc"></div>
                                </div>
                            </div>
                            
                            <div class="row">
                                <div class="form-group col-md-6">
                                    <label class="form-label font-weight-bolder">Productos por distribuidor:</label>
                                    <select id="producto" tabindex="2" class="select2 form-control productos">
                                        <option value="00000" selected disabled>-- SELECCIONE --</option>
                                        <?php echo $this->productos ?>
                                    </select>
                                    <div id="msj-producto"></div>
                                </div>
                                <div class="form-group col-md-6">
                                    <label class="form-label font-weight-bolder">SKU Verdum:</label>
                                    <select id="verdum" tabindex="3" class="select2 form-control verdum">
                                        <option value="00000" selected disabled>-- SELECCIONE --</option>
                                        <?php echo $this->filasver ?>
                                    </select>
                                    <div id="msj-verdum"></div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="form-group col-md-6">
                                    <label class="form-label font-weight-bolder">Stock mínimo:</label>
                                    <input id="minvalor" type="text" class="form-control" placeholder="Ejm: 1000" onkeypress='return solonumero(event)' autocomplete="off" />
                                    <div id="min-verdum"></div>
                                </div>
                                <div class="form-group col-md-6">
                                    <label class="form-label font-weight-bolder">Stock máximo:</label>
                                    <input id="maxvalor" type="text" class="form-control" placeholder="Ejm: 2000" onkeypress='return solonumero(event)' autocomplete="off" />
                                    <div id="max-verdum"></div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="form-group col-sm-4">
                                    <button id="btnregistrar" tabindex="3" type="button" class="btn btn-success btn-block"><i class="fa-solid fa-floppy-disk"></i><b>&nbsp;&nbsp;Guardar equivalencia</b></button>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>

                <section class="col-lg-12">
                    <div class="card col-12">
                        <div class="card-body">
                            <div class="row">

                                <div class="col-md-12 col-12">
                                    <table id="example1" class="table table-bordered">
                                        <thead class="thead-dark">
                                            <tr class="text-center">
                                                <th>#</th>
                                                <th>RUC</th>
                                                <th>RAZON SOCIAL</th>
                                                <th>SKU DISTRIBUIDOR</th>
                                                <th>SKU VERDUM</th>
                                                <th>DESCRIPCION PRODUCTO</th>
                                                <th>STOCK MINIMO</th>
                                                <th>STOCK MAXIMO</th>
                                                <th>#</th>
                                            </tr>
                                        </thead>
                                        <tbody id="table">
                                            <?php echo $this->filas ?>
                                        </tbody>
                                    </table>
                                </div>

                            </div>
                        </div>
                    </div>
                </section>
            </div>

        </div>
    </div>
    <!-- END: Content-->